Update tmsvr_packet.py
The basic example of Subscribing to the broadcast crashed with cryptic error:

techmanpy\clients\stateful_client.py", line 42, in keep_alive
    await self._listen_task
ValueError: malformed node or string on line 1: <ast.Name object at 0x000001E9C3FD4A90>


*The example*
def on_params(params):
   # broadcasted parameters received
   ...

conn.add_broadcast_callback(on_params)
await conn.keep_alive()


It crashes because ast.literal_eval will fail on the 'false' and 'true' values in the broadcast. I've added a .replace to make capitalize them. I've also added a try except to just give the raw value if conversion fails.